#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DVI-D-0 -d ● ● ●
bspc monitor HDMI-0 -d ● ● ●
bspc monitor DVI-D-1 -d ● ● ●

# source the colors.
# . "${HOME}/.cache/wal/colors.sh"
. "${HOME}/.config/polybar/colors/colors.sh"
# Set the border colors.
bspc config normal_border_color "$shade2"
bspc config active_border_color "$shade2"
bspc config focused_border_color "$shade4"

bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc monitor -f HDMI-0
